CREATE TABLE IF NOT EXISTS stoklar (
    id INT AUTO_INCREMENT PRIMARY KEY,
    urun_adi VARCHAR(255) NOT NULL,
    birim ENUM('Adet', 'Metre', 'KG', 'Paket') DEFAULT 'Adet',
    miktar DECIMAL(10,2) DEFAULT 0,
    kritik_esik DECIMAL(10,2) DEFAULT 5,
    alis_fiyat DECIMAL(10,2) DEFAULT 0,
    satis_fiyat DECIMAL(10,2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS isler (
    id INT AUTO_INCREMENT PRIMARY KEY,
    musteri_adi VARCHAR(255) NOT NULL,
    is_tanimi TEXT,
    personel_id INT,
    durum ENUM('Beklemede', 'Devam Ediyor', 'Tamamlandı', 'İptal') DEFAULT 'Beklemede',
    toplam_tutar DECIMAL(10,2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (personel_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS is_sarfiyat (
    id INT AUTO_INCREMENT PRIMARY KEY,
    is_id INT,
    stok_id INT,
    kullanilan_miktar DECIMAL(10,2) NOT NULL,
    birim_fiyat DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (is_id) REFERENCES isler(id) ON DELETE CASCADE,
    FOREIGN KEY (stok_id) REFERENCES stoklar(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
